### ISSUE TITLE
Bins by variable

### ISSUE THREAD

**Issue by dariomeili** [h4sci/horizontal-inequality#10]
The bins that separate the outcome variables into quintiles have to be calculated relative to only the subset that matters (I'm not sure if it does that at the moment). E.g. the quintiles have to be calculated only for one grouping variable ("grouping_var") and one weighting method ("measure").

**Comment by bonschorno** [comment]
We already do that by calculating the percentiles _after_ having filtered the relevant data. See changing numbers in the running app.
