### ISSUE TITLE
Year/Phase problem

### ISSUE THREAD

**Issue by dariomeili** [h4sci/horizontal-inequality#11]
The master file contains the year of data collection. As far as I know, @JanicBucheli separated them into DHS-Phases (i.e. survey rounds). As far as I remember, we had a problem there that there is an overlap in years between phases, right? 

Instead of using the phases, we could include a year slider in the UI and tell the app to always select the last available year for a given country before the year that is selected.

**Comment by dariomeili** [comment]
Any ideas on how to filter by "last available year below the selected year" for each country? Didn't find a solution so far on stackoverflow.

**Comment by bonschorno** [comment]
For the time being, I just added a lagged value.

**Comment by dariomeili** [comment]
the key was to arrange by country and year after filtering and then using slice() to select the newest obs.
