### ISSUE TITLE
Convert .dta files into open, text data

### ISSUE THREAD

**Issue by mbannert** [h4sci/horizontal-inequality#7]
I would convert the into a text based format or an .RData file at least. Note that git repositories are not so well suited for binaries. I would have a separate converter script to turn `raw_data` into `data`. In theory / the future you could even automate something to trigger conversion when a new file is pushed to `raw_data` (but I would not want to be distracted by that at this stage).

**Comment by bonschorno** [comment]
Alright, I'll fix that during the weekend so that non-STATA users can also work with the data!
